name: jtesta-ssh-mitm # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: modified ssh server to log sessions # 79 char long summary
description: |
  This is a modified ssh server to log sessions

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  openssh:
    # See 'snapcraft plugins'
    plugin: make
    source: .
    build-packages:
      - build-essential 
      - autoconf 
      - zlib1g-dev
    override-build: |
      cd openssl-1.0.2u
      ./config -v -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIC no-shared enable-weak-ssl-ciphers zlib
      make -j 1 depend
      make -j 1 all
      cd ../openssh-7.5p1-mitm
      autoconf
      ./configure --with-sandbox=no --with-privsep-user=ssh-mitm --with-privsep-path=/home/ssh-mitm/empty --with-pid-dir=/home/ssh-mitm --with-lastlog=/home/ssh-mitm --with-ssl-dir=../openssl-1.0.2u
      make -j 1
    override-prime: |
      snapcraftctl prime
      cp /root/parts/openssh/build/openssh-7.5p1-mitm/sshd /root/prime/sshd_mitm
      cp /root/parts/openssh/build/openssh-7.5p1-mitm/ssh /ssh
apps:
  jtesta-ssh-mitm:
    command: sshd_mitm
    plugs:
      - network
      - network-bind
      - home
  ssh:
    command: ssh
    plugs:
      - network
      - home
  
